name: Send Notification

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send Telegram Notification
      run: |
        curl -X POST https://api.telegram.org/bot8057972779:AAGG3SSVOUkG0VM_ycrIYgBrBrHUMpRMRy0/sendMessage \
        -d chat_id=-1001855473977 \
        -d text="A new PR was opened or a commit was pushed to the main branch!"
