#!/bin/bash

# Définir l'utilisateur GitHub (modifiez ce nom selon votre besoin)
USERNAME="trh4ckn0n"

# Récupération des informations de l'utilisateur via l'API GitHub
USER_NAME=$(curl -s "https://api.github.com/users/${USERNAME}" | jq -r '.name // "Nom non disponible"')
USER_LOGIN=$(curl -s "https://api.github.com/users/${USERNAME}" | jq -r '.login')
USER_AVATAR=$(curl -s "https://api.github.com/users/${USERNAME}" | jq -r '.avatar_url')

# Afficher les informations récupérées (pour vérifier)
echo "Nom de l'utilisateur : $USER_NAME"
echo "Identifiant GitHub : $USER_LOGIN"
echo "Avatar URL : $USER_AVATAR"

# Configuration des variables pour l'envoi Telegram
BOT_TOKEN="8057972779:AAGG3SSVOUkG0VM_ycrIYgBrBrHUMpRMRy0"
CHAT_ID="-1001855473977"

# Message à envoyer sur Telegram
MESSAGE="🔔 Nouvelle activité GitHub :\n\n- Action : workflow_dispatch\n- Type d'action : \n- Utilisateur : @$USER_LOGIN\n- Référentiel : trh4ckn0n/scrapnotif\n\n- Profil utilisateur : https://github.com/${USER_LOGIN} 👈 Allez voir votre profil GitHub pour plus de détails : https://github.com/${USER_LOGIN}\n\nAvatar : $USER_AVATAR"

# Envoi de la notification Telegram
curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
     -d "chat_id=${CHAT_ID}" \
     -d "text=${MESSAGE}"
     
# Optionnel : si vous souhaitez envoyer l'avatar comme photo dans Telegram
curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendPhoto" \
     -d "chat_id=${CHAT_ID}" \
     -d "photo=${USER_AVATAR}"
