name: Update README with Scraping Results

on:
  schedule:
    - cron: '0 0 * * *'  # Cela exécutera le workflow tous les jours à minuit
  push:
    branches:
      - main
  workflow_dispatch: # Permet d'exécuter le workflow manuellement

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper and update README
        run: |
          python scraper.py

      - name: Add all changes to git
        run: |
          git add -A  # Ajoute tous les fichiers non suivis au suivi Git
          git commit -m "Update README with latest scraping results" || echo "No changes to commit"

      - name: Push changes to repository
        run: |
          git push
