name: Update README with Scraping Results

on:
  schedule:
    - cron: '0 0 * * *'  # Exécution tous les jours à minuit
  push:
    branches:
      - main
  workflow_dispatch: # Permet d'exécuter manuellement

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run scraper and update README
        run: |
          python scraper.py

      - name: Configure git user
        run: |
          git config --global user.email "your_email@example.com"
          git config --global user.name "GitHub Actions"

      - name: Add all changes to git
        run: |
          git add -A
          git commit -m "Update README with latest scraping results" || echo "No changes to commit"

      - name: Push changes to repository
        run: |
          git push
