name: Mise à jour de la météo dans README

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permet d'exécuter manuellement
  schedule:
    - cron: "0 6 * * *"  # Exécution quotidienne à 6h UTC

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Vérification du code source
        uses: actions/checkout@v2

      - name: Installer les dépendances
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Exécuter le script météo
        run: |
          source venv/bin/activate
          METEO=$(python3 script_meteo.py)  # Cette commande doit retourner la météo au format texte brut

      - name: Mettre à jour la section météo dans README.md
        run: |
          # Remplacer la section météo dans README.md sans effacer le reste du fichier
          sed -i '/<!-- METEO_START -->/,/<!-- METEO_END -->/c\<!-- METEO_START -->\n$METEO\n<!-- METEO_END -->' README.md

      - name: Commit et push des changements dans README.md
        run: |
          git config --global user.email "trhacknon@proton.me"
          git config --global user.name "Trhacknon-bot"

          # Ajouter uniquement le fichier README.md
          git add README.md

          # Faire un commit si des changements sont présents
          git commit -m "Mise à jour de la météo dans README" || echo "Aucun changement à commit"

          # Récupérer les modifications distantes avant de pousser
          git pull origin main --no-rebase || echo "Pas de changements distants à récupérer"

          # Pousser les modifications dans le fichier README.md
          git push origin main
