name: Mise à jour de la météo dans README

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permet d'exécuter manuellement
  schedule:
    - cron: "0 6 * * *"  # Exécution quotidienne à 6h UTC

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Vérification du code source
        uses: actions/checkout@v2

      - name: Installer les dépendances
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Exécuter le script météo
        id: meteo
        run: |
          source venv/bin/activate
          METEO=$(python3 script_meteo.py)  # Cette commande doit retourner la météo au format texte brut
          echo "METEO=$METEO" >> $GITHUB_ENV  # Déclare METEO comme variable d'environnement

      - name: Générer le graphique d'humidité
        run: |
          source venv/bin/activate
      - name: Ajouter le contenu de README.md en haut de README.md
        run: |
          # Ajouter le contenu de README.md en haut de README.md
          cat READMEO.md README.md > temp_readme.md
          mv temp_readme.md README.md  # Remplacer README.md par la version mise à jour

      - name: Ajouter la section météo mise à jour à README.md
        run: |
          # Ajouter la section de météo mise à jour sous le contenu de README.md
          echo -e "\n## Météo actuelle\n$METEO" >> README.md

      - name: Ajouter humidity_chart.png au dépôt
        run: |
          git add humidity_chart.png  # Ajouter l'image au staging
          git commit -m "Ajouter le graphique d'humidité" || echo "Aucun changement à commit"  # Commit si nécessaire

      - name: Commit et push des changements dans README.md et humidity_chart.png
        run: |
          git config --global user.email "trhacknon@proton.me"
          git config --global user.name "Trhacknon-bot"

          # Ajouter uniquement les fichiers modifiés (README.md et humidity_chart.png)
          git add README.md
          git add humidity_chart.png

          # Faire un commit si des changements sont présents
          git commit -m "Mise à jour de la météo et ajout du graphique d'humidité" || echo "Aucun changement à commit"

          # Pousser les modifications dans le dépôt
          git push origin main
