name: Mise à jour de la météo dans README

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permet d'exécuter manuellement
  schedule:
    - cron: "0 6 * * *"  # Exécution quotidienne à 6h UTC

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Vérification du code source
        uses: actions/checkout@v2

      - name: Installer les dépendances
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Exécuter le script météo
        id: meteo
        run: |
          source venv/bin/activate
          METEO=$(python3 script_meteo.py)  # Cette commande doit retourner la météo au format texte brut
          echo "METEO=$METEO" >> $GITHUB_ENV  # Déclare METEO comme variable d'environnement

      - name: Ajouter le contenu de READMEO.md en haut de README.md
        run: |
          # Ajouter le contenu de READMEO.md en haut de README.md
          cat READMEO.md README.md > temp_readme.md
          mv temp_readme.md README.md  # Remplacer README.md par la version mise à jour

      - name: Ajouter la section météo mise à jour à README.md
        run: |
          # Ajouter la section de météo mise à jour sous le contenu ajouté de READMEO.md
          echo -e "\n## Météo actuelle\n$METEO" >> README.md

      - name: Commit et push des changements dans README.md
        run: |
          git config --global user.email "trhacknon@proton.me"
          git config --global user.name "Trhacknon-bot"

          # Ajouter uniquement le fichier README.md
          git add README.md

          # Faire un commit si des changements sont présents
          git commit -m "Mise à jour de la météo dans README" || echo "Aucun changement à commit"

          # Récupérer les modifications distantes avant de pousser
          git pull origin main --no-rebase || echo "Pas de changements distants à récupérer"

          # Pousser les modifications dans le fichier README.md
          git push origin main
